// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import NavBar from "./Navbar";
// import Head from "next/head";
// import { StreamedContentProvider } from '@/app/context/StreamedContent';
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <head>
//         <script src="https://accounts.google.com/gsi/client" async></script>
//       </head>
//       <body className={inter.className}>
//       <StreamedContentProvider> 
//         <NavBar />

//         {children}
//         <div id="portal" />

//         </StreamedContentProvider>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./Navbar";
import Head from "next/head";
import { StreamedContentProvider } from '@/app/context/StreamedContent';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://accounts.google.com/gsi/client" async></script>
      </head>
      <body className={inter.className}>
          
          {/* <NavBar /> */}
          {children}
          <div id="portal" />
          

      </body>
    </html>
  );
}